print("hello world")
print("hello again")
print("I like typing this")
print("this is fun")
print('Yay! Printing')
print(" I'd much rather than you 'not'")
print(' I "said" do not thouch this')
